
name: CleanerChat
version: 1.0
description: Allows players to set their own name colour and tidies vanilla chat.
author: RossGosling

main: uk.co.cherrygoose.cleanerchat.Main
database: false

commands:
    colour:
        description: "Displays your colour"